### ISSUE TITLE
Problem with the Ldtk loader when running from another project

### ISSUE THREAD

**Issue by Lukastos** [katharostech/bevy_retrograde#64]
Hi, 

first, thanks for the great work, it looks promising! I'm new to bevy and rust, thanks for your patience. I was trying to adapt the ldtk map loading for my project and I encountered some issues. I think it's a bug, but not 100% sure.

First, to test it, I ran the actual ldtk_map.rs example from the cloned repo, it works fine. Then, I moved the example to main.rs. It still compiles fine. Then, I also linked to the online crates what I could.

At this point I have:
`
[features]
default = ['ldtk']
ldtk = ["bevy_retrograde_ldtk"]

[dependencies]
bevy = {version = "0.5", default-features = false}

# bevy_retrograde_core = {version = "0.2", path = "crates/bevy_retrograde_core"}
bevy_retrograde_core = {version = "0.2"}
bevy_retrograde_ldtk = {version = "0.2", optional = true}
bevy_retrograde_macros = {version = "0.2"}
hex = "0.4.3"

[dev-dependencies]
hex = "0.4.3"
rand = "0.8.3"

[profile.dev]
debug = 0
opt-level = 1`
that I can run with _cargo run_. **This runs fine**. The _bevy_retrograde_ is still loaded from the _lib.rs_ !

Then I copy the exact same code (_main.rs_ and _Cargo.toml_) to my project. The difference is that the _lib.rs_ is not present, so I add the line:
`bevy_retrograde = "0.2"`
in the Cargo.toml file.  

But somehow running the same code from my project, it still compiles fine, but when running it, it panics: 

`Finished dev [unoptimized] target(s) in 26.22s
     Running `target/debug/my_project`
Oct 02 21:25:26.869  WARN bevy_asset::asset_server: no `AssetLoader` found for the following extension: ldtk
thread 'Compute Task Pool (4)' panicked at 'Requested resource does not exist: bevy_asset::assets::Assets<bevy_retrograde_ldtk::asset::LdtkMap>', /home/luc/.cargo/registry/src/github.com-1ecc6299db9ec823/bevy_ecs-0.5.0/src/system/system_param.rs:244:17
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at 'task has failed', /home/luc/.cargo/registry/src/github.com-1ecc6299db9ec823/async-task-4.0.3/src/task.rs:368:45`

However, if I copy the _lib.rs_ from the repo, it compiles and run fine (all the code is identical, so...yeah, makes sense ^^).

Am I missing something or is there an issue with loading the ldtk plugin from the crate?

**Comment by zicklag** [comment]
Hey there!

Sorry for the delay, I've been unavailable for the last bit, but I'm going to test this out and see why it's not working as soon as I can. It should be a simple fix, one way or the other.
